#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
# macOSのセキュリティ設定で、ターミナルにフルディスクアクセスを許可する必要がある
# 以下のコマンドを実行
# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ウィンドウがyabaiによって管理されるようにする
yabai -m config layout bsp

# ウィンドウをならべて表示したときの余白
yabai -m config \
    top_padding                  16             \
    bottom_padding               16             \
    left_padding                 16             \
    right_padding                16             \
    window_gap                   8             \

# マウスを使ってウィンドウを操作する
yabai -m config \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \

# global settings
yabai -m config                                 \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                off             \
    window_animation_duration    0.22            \
    window_animation_frame_rate  120            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \

# opacity settings
yabai -m config                                 \
    window_opacity               off             \
    window_opacity_duration      0.11            \
    # active_window_opacity        0.95            \
    # normal_window_opacity        0.70           \

# Alacrittyのみ透過
# yabai -m rule --add app="Alacritty" opacity=0.85

#  ╭──────────────────────────────────────────────────────────╮
#  │                      space settings                      │
#  ╰──────────────────────────────────────────────────────────╯
# yabai -m rule --add app="Arc" space=1
# yabai -m rule --add app='^Arc$' title='^Space.*$' manage=off

# yabai -m rule --add app="Alacritty" space=2
# yabai -m rule --add app="Google Chrome Canary" space=2
#
# yabai -m rule --add app="Slack" space=3
# yabai -m rule --add app="Discord" space=3
#
# yabai -m rule --add app="ChatGPT" space=4
#
# yabai -m rule --add app="Notion" space=5
# yabai -m rule --add app="Notion Calendar" space=5

#  ╭──────────────────────────────────────────────────────────╮
#  │ ここに書いたアプリはyabaiによって管理されない            │
#  ╰──────────────────────────────────────────────────────────╯
yabai -m rule --add app="^(Finder|Raycast|Fig|システム設定|Simulator|LINE|Cyberduck|Spotify|カレンダー|Google Chrome Canary)$" manage=off

echo "yabai configuration loaded.."
