#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
# macOSのセキュリティ設定で、ターミナルにフルディスクアクセスを許可する必要がある
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ウィンドウがyabaiによって管理されるようにする
yabai -m config layout bsp

# ウィンドウをならべて表示したときの余白
yabai -m config \
    top_padding                  0             \
    bottom_padding               0             \
    left_padding                 0             \
    right_padding                0             \
    window_gap                   0             \

# マウスを使ってウィンドウを操作する
yabai -m config \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \

# global settings
yabai -m config                                 \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \

# opacity settings
yabai -m config                                 \
    window_opacity               on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.85           \

# border settings
yabai -m config                                 \
    window_border                off            \
    active_window_border_color   0xff26578f     \
    normal_window_border_color   0xff0a1627     \
    window_border_width          4              \
    window_border_radius         2              \
    window_border_blur           off            \
    window_border_hidpi          on             \

#  ╭──────────────────────────────────────────────────────────╮
#  │                      space settings                      │
#  │                   うまく動いたらつかう                   │
#  ╰──────────────────────────────────────────────────────────╯
yabai -m rule --add app="Alacritty" space=1
yabai -m rule --add app="Firefox Developer Edition" space=2

# yabai -m rule --add app!="^(Google Chrome|Google Chrome Canary|Safari|Firefox|Figma|Logseq|Alacritty|Sidekick|Code|WezTerm|Friendly Streaming|Firefox Developer Edition|Slack)$" manage=off
 
#  ╭──────────────────────────────────────────────────────────╮
#  │ ここに書いたアプリはyabaiによって管理されない            │
#  ╰──────────────────────────────────────────────────────────╯
yabai -m rule --add app="^(Finder)$" manage=off

echo "yabai configuration loaded.."
